name: precious_life
description: "惜命应用旨在帮助用户更好地规划时间、获取有价值的信息并提供实用工具，从而珍惜生命、提高生活质量。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # 状态管理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 路由管理
  go_router: ^15.1.2

  # 数据序列化
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0

  # 工具
  uuid: ^4.0.0
  intl: ^0.19.0

  # UI组件
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.9

  # 存储
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  drift: ^2.14.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3

  # 网络
  dio: ^5.3.2
  # 电池信息
  battery_plus: ^6.2.1
  # 日历工具
  lunar: ^1.7.5
  # 国际化
  flutter_localizations:
    sdk: flutter
  # 定位
  geolocator: ^13.0.2
  geolocator_apple: ^2.3.9 # iOS/macOS 平台特定实现

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.0

  # 代码生成
  build_runner: ^2.4.6
  riverpod_generator: ^2.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  drift_dev: ^2.14.0
  # 图标生成
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/data/
  # 字体配置（可根据需要添加）
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
